### ISSUE TITLE
`build-args` won't be passed

### ISSUE THREAD

**Issue by d-koppenhagen** [cmgriffing/scully-gh-pages-action#1]
Hey, 

I tried to use the `build-args` option for deploying my scully blog via GH Pages.

My first try was like this:

```yml
...
      - uses: cmgriffing/scully-gh-pages-action@v4
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
          build-args: "--prod"
```

Which result log lokked like this:

```
...
Finished installing dependencies.
Ready to build your Scully site!
Building with: npm run build --prod
/usr/local/bin/npm run build --prod

> d-koppenhagen-website@0.0.0 build /home/runner/work/d-koppenhagen.de/d-koppenhagen.de
> ng build
...
```

As you can see in the last log line `ng build` is called without any arguments.
You can checkout the Pipeline here: https://github.com/d-koppenhagen/d-koppenhagen.de/runs/462023993

After this I realized that `ng build` is not called directly but by using `npm run build`. So I tried to pass through the args by using `-- --prod`:

```yml
...
      - uses: cmgriffing/scully-gh-pages-action@v4
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
          build-args: "-- --prod"
```

Unfortunately the result was the same:

```
...
Finished installing dependencies.
Ready to build your Scully site!
Building with: npm run build -- --prod
/usr/local/bin/npm run build -- --prod

> d-koppenhagen-website@0.0.0 build /home/runner/work/d-koppenhagen.de/d-koppenhagen.de
> ng build
...
```

Pipeline: https://github.com/d-koppenhagen/d-koppenhagen.de/runs/462027890

It seems that the build args are not passed through corretly.
To solve my issue, I needed to adjust my npm script, so that is includes the `--prod` flag directly:

```json
{
  ...
  "scripts": {
    ...
    "build": "ng build --prod",
  }
}
```

Now I didn't need any arguments:

```yml
...
      - uses: cmgriffing/scully-gh-pages-action@v4
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
```

And it works ✅ - but not by using the `build-args` ❌:

```
...
Finished installing dependencies.
Ready to build your Scully site!
Building with: npm run build 
/usr/local/bin/npm run build 

> d-koppenhagen-website@0.0.0 build /home/runner/work/d-koppenhagen.de/d-koppenhagen.de
> ng build --prod ""
...
```

You can see `--prod` is called and the result contains a real production build.

**Comment by d-koppenhagen** [comment]
Btw: the working pipeline is here: https://github.com/d-koppenhagen/d-koppenhagen.de/runs/462037759

**Comment by cmgriffing** [comment]
Thanks. I pushed up a v5 that fixes this issue. Please test it out when you can and let me know.

**Comment by d-koppenhagen** [comment]
LGTM! Thanks for fixing it
