### ISSUE TITLE
Standard workflow fails to download action from repository

### ISSUE THREAD

**Issue by rikr2sanchez** [cmgriffing/scully-gh-pages-action#10]
![image](https://user-images.githubusercontent.com/19697749/90354040-04a44c00-e016-11ea-8a65-d0697d562a4f.png)

**Comment by cmgriffing** [comment]
Apologies. The README is out of date. The latest version of the action is v9. I will get the README updated.

**Comment by rikr2sanchez** [comment]
Oh no, the apologies are mine for not noticing the detail. Thank you !

**Comment by cmgriffing** [comment]
Thanks again for pointing this out and creating the PR. With it merged, I am going to close the issue now.
