### ISSUE TITLE
bug: workflow failes with angular 12

### ISSUE THREAD

**Issue by d-koppenhagen** [cmgriffing/scully-gh-pages-action#14]
Running the workflow in an angular12 repo failes.

Here is an example:
https://github.com/d-koppenhagen/d-koppenhagen.de/runs/2623270287?check_suite_focus=true

The log shows:

```log
Run cmgriffing/scully-gh-pages-action@v9
  with:
    access-token: ***
    deploy-branch: gh-pages
    build-args: --prod
[@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead
Installing your site's dependencies using npm.
/usr/local/bin/npm ci
npm ERR! string.prototype.trimend not accessible from es-abstract

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-05-19T18_37_19_483Z-debug.log
Error: The process '/usr/local/bin/npm' failed with exit code 1
```

Poroably the problem is that angular 12 requires a node version of `node: '^12.14.1 || ^14.0.0'`.
In the workflow `actions.yml` the used node version is just set to `12`.

Are you able to verify the problem?

**Comment by cmgriffing** [comment]
Oh that makes sense. Thanks for the catch. I will work on this in the next couple days.

**Comment by cmgriffing** [comment]
I have created a pre-release.

https://github.com/cmgriffing/scully-gh-pages-action/releases/tag/v10-test1

I will test it on my older Angular project. 

@d-koppenhagen  Could you test it on yours that is on version 12?

**Comment by cmgriffing** [comment]
Ok, so after some fiddling, it seems the ideal fix is to explicitly set node version in a project's workflow using setup-node.

A section has been added to the README.

Thanks for pointing it out still.

**Comment by d-koppenhagen** [comment]
hey @cmgriffing : i tried it out to use node14 as described in the README. Unfortunately I will run into the same issue.

**Comment by d-koppenhagen** [comment]
Okay, I solved my problem.
On my local machine I used node.js 16 instead of node.js 14. That caused, my `package-lock.json` file was slightly different and during `npm ci`, the exact versions of my node_modules were installed in the ci.
Anyway: Thanks for your support!
