### ISSUE TITLE
Bug: action never finishes (Scully2, Angular13, Node.js16)

### ISSUE THREAD

**Issue by d-koppenhagen** [cmgriffing/scully-gh-pages-action#17]
Running `scully-gh-pages-action` with the newest version of scully, Angular 13 and Node.js 16 will perform all needed actions but the comand seems not to finish after the last log: `Enjoy! ✨`.

*Examples:*
- https://github.com/d-koppenhagen/scully-plugins/runs/4499186238?check_suite_focus=true
- https://github.com/d-koppenhagen/k9n.dev/runs/4489212489?check_suite_focus=true

**Comment by cmgriffing** [comment]
Oh interesting. Thanks for the report. I will take a look.

**Comment by d-koppenhagen** [comment]
Probably an `exit 0` would help?
