### ISSUE TITLE
Scully build changed: provide `--nw` flag by default

### ISSUE THREAD

**Issue by d-koppenhagen** [cmgriffing/scully-gh-pages-action#2]
Hey, recently a new version of scully has been published.
With it, watch mode has been turned on by default.
In fact, so stop running in watch mode during GH actions build, the flas `--nw` should be added by default here: https://github.com/cmgriffing/scully-gh-pages-action/blob/master/index.js#L38

See the scully PR: https://github.com/scullyio/scully/commit/ae3a04a993c8df29b76eb6bdd53057c91cdfbeed

**Comment by cmgriffing** [comment]
Sorry for the delay. I will get that added over the next day or so.

**Comment by cmgriffing** [comment]
To do this and not break any existing configs I mixed it into the arg cleanup. See the latest release.

**Comment by d-koppenhagen** [comment]
LGTM, thanks!
