### ISSUE TITLE
Cannot read properties of undefined (reading '@scullyio/scully')

### ISSUE THREAD

**Issue by riethmue** [cmgriffing/scully-gh-pages-action#28]
Hi,
unfortunately my build using scully-gh-pages-action fails with

`Finished building your site.
Determine Scully version from './package-lock.json'.
Error: Cannot read properties of undefined (reading '@scullyio/scully')`

I checked my [package-lock.json](https://github.com/riethmue/riethmue.github.io/blob/master/package-lock.json) and scully is listed:
```

      "dependencies": {
        "@scullyio/scully": "^2.1.41",
        ...
      },
```

I would be very thankful if anyone could help me with this issue!

**Comment by cmgriffing** [comment]
This wax autoclosed due to a recent merged PR. If you are still running into problems, please recreate the Issue.
