### ISSUE TITLE
Simplify args

### ISSUE THREAD

**Issue by d-koppenhagen** [cmgriffing/scully-gh-pages-action#3]
One more suggestion from me:

With the current version it’s necessary to pass arguments for scully and angular with extra `--` like so:

```yml
build-args: "-- --prod"
scully-args: "-- --nw"
```

This is necessary as the pipleline internally calles the npm run script instead of the commands directly (`npm run scully`, `npm run build` instead of `scully` and `ng build`).

For me this seems a bit odd as when I will use the pipeline and see `build-args` my first thought was just to add the arg without any extra dashes, as this are the args for `scully` and `ng build` and not for the npm scripts:

```yml
build-args: "--prod"
scully-args: "--nw"
```

So I think it would be great to simplify it or even allow both ways (cut extra dashes from the arg and add them by default).

As the pipeline will have a new version this shouldn’t be an issue for old implementations (as long they are not upgrading blindly).

Btw: great project 👍🏼

**Comment by cmgriffing** [comment]
Thanks. The latest commit solves this in my limited testing.

**Comment by d-koppenhagen** [comment]
Perfect, it works :)
