### ISSUE TITLE
deploy to another repo?

### ISSUE THREAD

**Issue by phodal** [cmgriffing/scully-gh-pages-action#6]
Hi, would you like to support a development repo, and deploy in anthoer repo?

**Comment by cmgriffing** [comment]
I think you could put the action on the deploy repo and just make PRs to that repo from your development one. That should work just fine.

**Comment by phodal** [comment]
In the another way. I don't want to use `gh-pages` branch in my development repo, so I use another repo for deployment.

here is my dev repo: https://github.com/phodal/ledge/

here is deploy repo: https://github.com/phodal/do/

**Comment by cmgriffing** [comment]
You dont have to use the gh-pages branch. The default is `master`.

See this section of the README: https://github.com/cmgriffing/scully-gh-pages-action#knobs--handles

The default branch is `master` which seems like what you want anyway.

**Comment by phodal** [comment]
thanks
